//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGMKTStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBEmployee
    {
        public long EmployeeId { get; set; }
        public string EmployeeTypeId { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeIdRef { get; set; }
        public string EmployeeUsername { get; set; }
        public string EmployeePassword { get; set; }
        public Nullable<int> EmployeeStatus { get; set; }
    }
}
