//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGMKTStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBLogTradeOfCustomer
    {
        public long LogTradeOfCusId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string Instrument { get; set; }
        public string BuySell { get; set; }
        public string OpenClose { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> Realized { get; set; }
        public Nullable<decimal> Urealized { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public string StatusId { get; set; }
    }
}
