//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGMKTStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBMarketPrice
    {
        public long MarketPriceId { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string Instrument { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateBy { get; set; }
    }
}
