//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGMKTStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBTradeClose
    {
        public long TradeCloseId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<System.DateTime> TradeCloseDate { get; set; }
        public string OpenInstrument { get; set; }
        public Nullable<int> OpenVolume { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> OpenAvgPrice { get; set; }
        public Nullable<int> CloseVolume { get; set; }
        public Nullable<decimal> ClosePrice { get; set; }
        public Nullable<int> InterestCalPercent { get; set; }
        public Nullable<decimal> InterestCalSum { get; set; }
        public string BuySell { get; set; }
        public string OpenClose { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public string StatusId { get; set; }
        public Nullable<long> TradeOpenIdRef { get; set; }
    }
}
