//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGMKTStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBTradeOpenStatusId
    {
        public string TradeOpenStatusId { get; set; }
        public string TradeOpenStatusName { get; set; }
        public string TradeOpenStatusDetails { get; set; }
    }
}
